version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: DB_KP_K
    restart: always
    environment:
      POSTGRES_DB: DB_KP
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: 1q2w3e4r
    ports:
      - "5433:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
